apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-api
  labels:
    app: ids-api
spec:
  # Nếu autoscaling.enabled = true → bỏ replicas
  replicas: {{ if not (.Values.autoscaling.enabled | default false) }}{{ .Values.replicaCount }}{{ end }}

  selector:
    matchLabels:
      app: ids-api

  template:
    metadata:
      labels:
        app: ids-api
    spec:
      containers:
      - name: ids-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.containerPort }}

        env:
        - name: MODEL_BUCKET
          value: "{{ .Values.model.bucket }}"
        - name: MODEL_VERSION
          value: "{{ .Values.model.version }}"

        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 20

        resources:
{{- toYaml .Values.resources | nindent 10 }}
