name: Build and Push MLflow Image

on:
  push:
    branches: [main]
    paths:
      - "mlflow/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set dynamic image tag
        id: vars
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Login DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t bqmxnh/mlflow:pg ./mlflow
          docker tag bqmxnh/mlflow:pg bqmxnh/mlflow:${{ steps.vars.outputs.tag }}

      - name: Push Docker image
        run: |
          docker push bqmxnh/mlflow:pg
          docker push bqmxnh/mlflow:${{ steps.vars.outputs.tag }}

      - name: Trigger Helm Chart Update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Update Helm Chart"
          repo: bqmxnh/manifests-cloud-ops
          ref: "main"
          token: ${{ secrets.PAT_TOKEN }}
          inputs: |
            {"image_tag": "${{ steps.vars.outputs.tag }}", "service": "mlflow"}

