name: Build Retrain Image

on:
  push:
    paths:
      - "retrain/**"
      - ".github/workflows/build-retrain.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Generate dynamic tag
        id: vars
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build retrain image
        run: |
          docker build -t bqmxnh/cloud-ops-retrain:${{ steps.vars.outputs.tag }} \
                       -t bqmxnh/cloud-ops-retrain:latest retrain

      - name: Push retrain images
        run: |
          docker push bqmxnh/cloud-ops-retrain:${{ steps.vars.outputs.tag }}
          docker push bqmxnh/cloud-ops-retrain:latest

      - name: Trigger Helm Chart Update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Update Helm Chart"
          repo: bqmxnh/manifests-cloud-ops
          ref: "main"
          token: ${{ secrets.PAT_TOKEN }}
          inputs: |
            {"image_tag": "${{ steps.vars.outputs.tag }}", "service": "retrain"}
