name: Build Retrain Image

on:
  push:
    paths:
      - "retrain/**"
      - ".github/workflows/build-retrain.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Login Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build retrain image
        run: |
            docker build -t bqmxnh/cloud-ops-retrain:${{ github.sha }} retrain

      - name: Push retrain image
        run: |
            docker push bqmxnh/cloud-ops-retrain:${{ github.sha }}

