name: Build and Push API Image

on:
  push:
    branches: [main]
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set dynamic image tag
        id: vars
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Login DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t bqmxnh/arf-ids-api:latest ./api
          docker tag bqmxnh/arf-ids-api:latest bqmxnh/arf-ids-api:${{ steps.vars.outputs.tag }}

      - name: Push Docker image
        run: |
          docker push bqmxnh/arf-ids-api:latest
          docker push bqmxnh/arf-ids-api:${{ steps.vars.outputs.tag }}

      - name: Trigger Helm Chart Update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Update Helm Chart"
          ref: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{"image_tag": "${{ steps.vars.outputs.tag }}"}'
